### ISSUE TITLE
[bug] Grid layout features isn't used.

### ISSUE THREAD

**Issue by RredCat** [denoolen/test1#1]
Grid layout functionality isn't used.

**Current implementation:** We position elements with Margin.
**Expected implementation:** Use rows and columns for placing elements.

Use next resources for inspiration:
[Grid Layout in WPF](https://www.c-sharpcorner.com/UploadFile/1e050f/grid-layout-in-wpf/)
[Grid Class](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.grid?view=net-5.0)

**Comment by denoolen** [comment]
Done
