### ISSUE TITLE
[Task] Create Person entity

### ISSUE THREAD

**Issue by RredCat** [denoolen/test1#2]
Create Person entity with next properties: Name, Surname, Age. 
It has to look something like this - [Person.cs](https://github.com/dizheleva/SoftUni-Courses/blob/0261260d65b77a4809e200bf8b36021f151e02b4/C%23%20Advanced/C%23%20Advanced/06.%20Defining%20Classes%20-%20Exercise/01-04.%20Opinion%20Poll/Person.cs)

**Comment by denoolen** [comment]
Done
